### ISSUE TITLE
pattern: simple YAML templating with input parameters

### ISSUE THREAD

**Issue by dlespiau** [jkcfg/jk#121]
It would be nice to document a few patterns people may want to do. A first, simple, one we can think about is YAML templating with input parameters:

```js
import std from "std";
import * as k8s from "@jkcfg/kubernetes/api";

const params = {
  name: std.param.String("name", "consul"),
  port: std.param.Number("port", 80)
};

const service = new k8s.core.v1.Service(params.name, {
  metadata: {
    labels: {
      component: params.name
    }
  },
  spec: {
    selector: {
      component: params.name
    },
    ports: [{
      name: "http",
      port: params.port
    }]
  }
});

std.write(service, "console-service.yaml");
```
```
jk run -v -p port=8080 service.js
```
```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    component: consul
  name: consul
spec:
  ports:
  - name: http
    port: 8080
  selector:
    component: consul
```
