### ISSUE TITLE
passing objects to params command

### ISSUE THREAD

**Issue by jaxxstorm** [jkcfg/jk#187]
It's possible to define a param as an object, for example:

```
ingress:
  publicHosts:
  - domain: foo.example.com
    paths:
    - path: /foo
      service: foo.ns.svc
      port: 80
    - path: /bar
      service: bar.ns.svc
      port: 90
  - domain: bar.example.com
    paths:
    - path: /foo
      service: foo.ns.svc
      port: 80
    - path: /bar
      service: bar.ns.svc
      port: 90
```

Is it possible to override these params using the `-p` option?
